# Análise Estatística
```
Tema: Impacto da IA e das redes sociais na saúde e notas dos alunos
```
---

In [1]:
import polars as pl
import time

## Big Data e Processamento Otimizado com Python II

### Manipulação do Parquet e StringCache
---

In [3]:
inicial = (
    pl.scan_parquet("estudantes.parquet"))

display(inicial.collect())

shape: (500_000, 48)
┌───────────┬───────────┬───────────┬───────────┬───┬───────────┬───────────┬───────────┬──────────┐
│ id_estuda ┆ pais      ┆ nivel_des ┆ taxa_pobr ┆ … ┆ pontuacao ┆ indice_be ┆ pontuacao ┆ pontuaca │
│ nte       ┆ ---       ┆ envolvime ┆ eza_perce ┆   ┆ _vicio_di ┆ m_estar   ┆ _risco_ac ┆ o_risco_ │
│ ---       ┆ str       ┆ nto       ┆ ntual     ┆   ┆ gital     ┆ ---       ┆ ademico   ┆ financei │
│ i64       ┆           ┆ ---       ┆ ---       ┆   ┆ ---       ┆ f64       ┆ ---       ┆ ro       │
│           ┆           ┆ str       ┆ f64       ┆   ┆ f64       ┆           ┆ f64       ┆ ---      │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆ f64      │
╞═══════════╪═══════════╪═══════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪══════════╡
│ 1         ┆ Catar     ┆ Em desenv ┆ 16.3      ┆ … ┆ 8.18      ┆ 66.66     ┆ 0.0       ┆ 26.52    │
│           ┆           ┆ olvimento ┆           ┆   ┆           ┆           ┆           ┆          │
│ 2         ┆ Estados   ┆ Desenvolv ┆ 8.75      ┆ … ┆ 22.07     ┆ 43.89     ┆ 0.0       ┆ 39.26    │
│           ┆ Unidos    ┆ ido       ┆           ┆   ┆           ┆           ┆           ┆          │
│ 3         ┆ México    ┆ Em desenv ┆ 23.64     ┆ … ┆ 12.59     ┆ 65.48     ┆ 0.0       ┆ 47.54    │
│           ┆           ┆ olvimento ┆           ┆   ┆           ┆           ┆           ┆          │
│ 4         ┆ Canadá    ┆ Desenvolv ┆ 14.51     ┆ … ┆ 8.01      ┆ 57.91     ┆ 0.0       ┆ 23.44    │
│           ┆           ┆ ido       ┆           ┆   ┆           ┆           ┆           ┆          │
│ 5         ┆ Sri Lanka ┆ Subdesenv ┆ 62.28     ┆ … ┆ 21.55     ┆ 53.69     ┆ 0.0       ┆ 47.31    │
│           ┆           ┆ olvido    ┆           ┆   ┆           ┆           ┆           ┆          │
│ …         ┆ …         ┆ …         ┆ …         ┆ … ┆ …         ┆ …         ┆ …         ┆ …        │
│ 499996    ┆ Canadá    ┆ Desenvolv ┆ 14.51     ┆ … ┆ 26.53     ┆ 52.82     ┆ 0.0       ┆ 66.51    │
│           ┆           ┆ ido       ┆           ┆   ┆           ┆           ┆           ┆          │
│ 499997    ┆ Países    ┆ Desenvolv ┆ 14.7      ┆ … ┆ 17.95     ┆ 57.49     ┆ 0.0       ┆ 42.45    │
│           ┆ Baixos    ┆ ido       ┆           ┆   ┆           ┆           ┆           ┆          │
│ 499998    ┆ Singapura ┆ Desenvolv ┆ 7.12      ┆ … ┆ 14.19     ┆ 55.45     ┆ 0.0       ┆ 31.99    │
│           ┆           ┆ ido       ┆           ┆   ┆           ┆           ┆           ┆          │
│ 499999    ┆ Paquistão ┆ Subdesenv ┆ 44.14     ┆ … ┆ 12.9      ┆ 56.26     ┆ 0.0       ┆ 33.07    │
│           ┆           ┆ olvido    ┆           ┆   ┆           ┆           ┆           ┆          │
│ 500000    ┆ Reino     ┆ Desenvolv ┆ 12.32     ┆ … ┆ 23.77     ┆ 42.46     ┆ 0.0       ┆ 57.76    │
│           ┆ Unido     ┆ ido       ┆           ┆   ┆           ┆           ┆           ┆          │
└───────────┴───────────┴───────────┴───────────┴───┴───────────┴───────────┴───────────┴──────────┘

### Filtros
```
Para selecionar linhas baseadas em condições lógicas (semelhante ao WHERE do SQL).
```
---

In [8]:
# Filtro Simples: Apenas estudantes de Singapura
q_singapura = inicial.filter(pl.col("pais") == "Singapura")

# Filtro Composto (E / OU): Singapura e idade maior que 20
q_singapura_pobreza = inicial.filter(
    (pl.col("pais") == "Singapura") & (pl.col("idade") > 20)
)

# Filtro com Lista (IS IN): Apenas paises desenvolvidos
q_desenvolvidos = inicial.filter(
    pl.col("nivel_desenvolvimento").is_in(["Desenvolvido"])
)

display(q_singapura.collect())
display(q_singapura_pobreza.collect())
display(q_desenvolvidos.collect())

shape: (9_876, 48)
┌───────────┬───────────┬───────────┬───────────┬───┬───────────┬───────────┬───────────┬──────────┐
│ id_estuda ┆ pais      ┆ nivel_des ┆ taxa_pobr ┆ … ┆ pontuacao ┆ indice_be ┆ pontuacao ┆ pontuaca │
│ nte       ┆ ---       ┆ envolvime ┆ eza_perce ┆   ┆ _vicio_di ┆ m_estar   ┆ _risco_ac ┆ o_risco_ │
│ ---       ┆ str       ┆ nto       ┆ ntual     ┆   ┆ gital     ┆ ---       ┆ ademico   ┆ financei │
│ i64       ┆           ┆ ---       ┆ ---       ┆   ┆ ---       ┆ f64       ┆ ---       ┆ ro       │
│           ┆           ┆ str       ┆ f64       ┆   ┆ f64       ┆           ┆ f64       ┆ ---      │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆ f64      │
╞═══════════╪═══════════╪═══════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪══════════╡
│ 100       ┆ Singapura ┆ Desenvolv ┆ 7.12      ┆ … ┆ 16.16     ┆ 43.01     ┆ 0.0       ┆ 29.15    │
│           ┆           ┆ ido       ┆           ┆   ┆           ┆           ┆           ┆          │
│ 197       ┆ Singapura ┆ Desenvolv ┆ 7.12      ┆ … ┆ 20.72     ┆ 57.91     ┆ 0.0       ┆ 31.35    │
│           ┆           ┆ ido       ┆           ┆   ┆           ┆           ┆           ┆          │
│ 267       ┆ Singapura ┆ Desenvolv ┆ 7.12      ┆ … ┆ 15.08     ┆ 64.5      ┆ 0.0       ┆ 35.73    │
│           ┆           ┆ ido       ┆           ┆   ┆           ┆           ┆           ┆          │
│ 394       ┆ Singapura ┆ Desenvolv ┆ 7.12      ┆ … ┆ 17.99     ┆ 76.1      ┆ 0.0       ┆ 17.69    │
│           ┆           ┆ ido       ┆           ┆   ┆           ┆           ┆           ┆          │
│ 411       ┆ Singapura ┆ Desenvolv ┆ 7.12      ┆ … ┆ 17.63     ┆ 41.17     ┆ 0.0       ┆ 33.31    │
│           ┆           ┆ ido       ┆           ┆   ┆           ┆           ┆           ┆          │
│ …         ┆ …         ┆ …         ┆ …         ┆ … ┆ …         ┆ …         ┆ …         ┆ …        │
│ 499869    ┆ Singapura ┆ Desenvolv ┆ 7.12      ┆ … ┆ 23.19     ┆ 46.59     ┆ 0.0       ┆ 61.13    │
│           ┆           ┆ ido       ┆           ┆   ┆           ┆           ┆           ┆          │
│ 499903    ┆ Singapura ┆ Desenvolv ┆ 7.12      ┆ … ┆ 20.52     ┆ 47.04     ┆ 0.0       ┆ 39.26    │
│           ┆           ┆ ido       ┆           ┆   ┆           ┆           ┆           ┆          │
│ 499939    ┆ Singapura ┆ Desenvolv ┆ 7.12      ┆ … ┆ 19.11     ┆ 69.82     ┆ 0.0       ┆ 48.28    │
│           ┆           ┆ ido       ┆           ┆   ┆           ┆           ┆           ┆          │
│ 499945    ┆ Singapura ┆ Desenvolv ┆ 7.12      ┆ … ┆ 21.35     ┆ 54.08     ┆ 0.0       ┆ 57.9     │
│           ┆           ┆ ido       ┆           ┆   ┆           ┆           ┆           ┆          │
│ 499998    ┆ Singapura ┆ Desenvolv ┆ 7.12      ┆ … ┆ 14.19     ┆ 55.45     ┆ 0.0       ┆ 31.99    │
│           ┆           ┆ ido       ┆           ┆   ┆           ┆           ┆           ┆          │
└───────────┴───────────┴───────────┴───────────┴───┴───────────┴───────────┴───────────┴──────────┘

shape: (4_450, 48)
┌───────────┬───────────┬───────────┬───────────┬───┬───────────┬───────────┬───────────┬──────────┐
│ id_estuda ┆ pais      ┆ nivel_des ┆ taxa_pobr ┆ … ┆ pontuacao ┆ indice_be ┆ pontuacao ┆ pontuaca │
│ nte       ┆ ---       ┆ envolvime ┆ eza_perce ┆   ┆ _vicio_di ┆ m_estar   ┆ _risco_ac ┆ o_risco_ │
│ ---       ┆ str       ┆ nto       ┆ ntual     ┆   ┆ gital     ┆ ---       ┆ ademico   ┆ financei │
│ i64       ┆           ┆ ---       ┆ ---       ┆   ┆ ---       ┆ f64       ┆ ---       ┆ ro       │
│           ┆           ┆ str       ┆ f64       ┆   ┆ f64       ┆           ┆ f64       ┆ ---      │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆ f64      │
╞═══════════╪═══════════╪═══════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪══════════╡
│ 100       ┆ Singapura ┆ Desenvolv ┆ 7.12      ┆ … ┆ 16.16     ┆ 43.01     ┆ 0.0       ┆ 29.15    │
│           ┆           ┆ ido       ┆           ┆   ┆           ┆           ┆           ┆          │
│ 394       ┆ Singapura ┆ Desenvolv ┆ 7.12      ┆ … ┆ 17.99     ┆ 76.1      ┆ 0.0       ┆ 17.69    │
│           ┆           ┆ ido       ┆           ┆   ┆           ┆           ┆           ┆          │
│ 411       ┆ Singapura ┆ Desenvolv ┆ 7.12      ┆ … ┆ 17.63     ┆ 41.17     ┆ 0.0       ┆ 33.31    │
│           ┆           ┆ ido       ┆           ┆   ┆           ┆           ┆           ┆          │
│ 499       ┆ Singapura ┆ Desenvolv ┆ 7.12      ┆ … ┆ 17.64     ┆ 43.39     ┆ 0.0       ┆ 39.2     │
│           ┆           ┆ ido       ┆           ┆   ┆           ┆           ┆           ┆          │
│ 620       ┆ Singapura ┆ Desenvolv ┆ 7.12      ┆ … ┆ 8.94      ┆ 64.26     ┆ 0.0       ┆ 24.56    │
│           ┆           ┆ ido       ┆           ┆   ┆           ┆           ┆           ┆          │
│ …         ┆ …         ┆ …         ┆ …         ┆ … ┆ …         ┆ …         ┆ …         ┆ …        │
│ 499682    ┆ Singapura ┆ Desenvolv ┆ 7.12      ┆ … ┆ 6.95      ┆ 72.03     ┆ 0.0       ┆ 23.96    │
│           ┆           ┆ ido       ┆           ┆   ┆           ┆           ┆           ┆          │
│ 499697    ┆ Singapura ┆ Desenvolv ┆ 7.12      ┆ … ┆ 19.58     ┆ 40.18     ┆ 0.0       ┆ 43.2     │
│           ┆           ┆ ido       ┆           ┆   ┆           ┆           ┆           ┆          │
│ 499818    ┆ Singapura ┆ Desenvolv ┆ 7.12      ┆ … ┆ 17.79     ┆ 59.29     ┆ 0.0       ┆ 39.14    │
│           ┆           ┆ ido       ┆           ┆   ┆           ┆           ┆           ┆          │
│ 499869    ┆ Singapura ┆ Desenvolv ┆ 7.12      ┆ … ┆ 23.19     ┆ 46.59     ┆ 0.0       ┆ 61.13    │
│           ┆           ┆ ido       ┆           ┆   ┆           ┆           ┆           ┆          │
│ 499939    ┆ Singapura ┆ Desenvolv ┆ 7.12      ┆ … ┆ 19.11     ┆ 69.82     ┆ 0.0       ┆ 48.28    │
│           ┆           ┆ ido       ┆           ┆   ┆           ┆           ┆           ┆          │
└───────────┴───────────┴───────────┴───────────┴───┴───────────┴───────────┴───────────┴──────────┘

shape: (149_548, 48)
┌───────────┬───────────┬───────────┬───────────┬───┬───────────┬───────────┬───────────┬──────────┐
│ id_estuda ┆ pais      ┆ nivel_des ┆ taxa_pobr ┆ … ┆ pontuacao ┆ indice_be ┆ pontuacao ┆ pontuaca │
│ nte       ┆ ---       ┆ envolvime ┆ eza_perce ┆   ┆ _vicio_di ┆ m_estar   ┆ _risco_ac ┆ o_risco_ │
│ ---       ┆ str       ┆ nto       ┆ ntual     ┆   ┆ gital     ┆ ---       ┆ ademico   ┆ financei │
│ i64       ┆           ┆ ---       ┆ ---       ┆   ┆ ---       ┆ f64       ┆ ---       ┆ ro       │
│           ┆           ┆ str       ┆ f64       ┆   ┆ f64       ┆           ┆ f64       ┆ ---      │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆ f64      │
╞═══════════╪═══════════╪═══════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪══════════╡
│ 2         ┆ Estados   ┆ Desenvolv ┆ 8.75      ┆ … ┆ 22.07     ┆ 43.89     ┆ 0.0       ┆ 39.26    │
│           ┆ Unidos    ┆ ido       ┆           ┆   ┆           ┆           ┆           ┆          │
│ 4         ┆ Canadá    ┆ Desenvolv ┆ 14.51     ┆ … ┆ 8.01      ┆ 57.91     ┆ 0.0       ┆ 23.44    │
│           ┆           ┆ ido       ┆           ┆   ┆           ┆           ┆           ┆          │
│ 8         ┆ Japão     ┆ Desenvolv ┆ 6.56      ┆ … ┆ 12.97     ┆ 57.09     ┆ 0.0       ┆ 59.34    │
│           ┆           ┆ ido       ┆           ┆   ┆           ┆           ┆           ┆          │
│ 10        ┆ Alemanha  ┆ Desenvolv ┆ 10.99     ┆ … ┆ 11.75     ┆ 54.35     ┆ 0.0       ┆ 19.34    │
│           ┆           ┆ ido       ┆           ┆   ┆           ┆           ┆           ┆          │
│ 11        ┆ Dinamarca ┆ Desenvolv ┆ 5.21      ┆ … ┆ 12.07     ┆ 62.98     ┆ 0.0       ┆ 42.27    │
│           ┆           ┆ ido       ┆           ┆   ┆           ┆           ┆           ┆          │
│ …         ┆ …         ┆ …         ┆ …         ┆ … ┆ …         ┆ …         ┆ …         ┆ …        │
│ 499995    ┆ Suécia    ┆ Desenvolv ┆ 11.01     ┆ … ┆ 19.76     ┆ 47.73     ┆ 0.0       ┆ 38.16    │
│           ┆           ┆ ido       ┆           ┆   ┆           ┆           ┆           ┆          │
│ 499996    ┆ Canadá    ┆ Desenvolv ┆ 14.51     ┆ … ┆ 26.53     ┆ 52.82     ┆ 0.0       ┆ 66.51    │
│           ┆           ┆ ido       ┆           ┆   ┆           ┆           ┆           ┆          │
│ 499997    ┆ Países    ┆ Desenvolv ┆ 14.7      ┆ … ┆ 17.95     ┆ 57.49     ┆ 0.0       ┆ 42.45    │
│           ┆ Baixos    ┆ ido       ┆           ┆   ┆           ┆           ┆           ┆          │
│ 499998    ┆ Singapura ┆ Desenvolv ┆ 7.12      ┆ … ┆ 14.19     ┆ 55.45     ┆ 0.0       ┆ 31.99    │
│           ┆           ┆ ido       ┆           ┆   ┆           ┆           ┆           ┆          │
│ 500000    ┆ Reino     ┆ Desenvolv ┆ 12.32     ┆ … ┆ 23.77     ┆ 42.46     ┆ 0.0       ┆ 57.76    │
│           ┆ Unido     ┆ ido       ┆           ┆   ┆           ┆           ┆           ┆          │
└───────────┴───────────┴───────────┴───────────┴───┴───────────┴───────────┴───────────┴──────────┘

### Seleção e Exclusão
```
Para escolher ou remover colunas específicas.
```
---

In [10]:
# Selecionar apenas colunas de interesse
q_simples = inicial.select(["pais", "nivel_desenvolvimento", "idade"])

# .drop() remove as colunas listadas
q_sem_codigos = inicial.drop(["indice_infraestrutura_internet","velocidade_media_internet_mbps"])

# Seleciona tudo (implícito) excluindo as colunas listadas
q_sem_codigos = inicial.select(pl.exclude(["indice_infraestrutura_internet","velocidade_media_internet_mbps"]))

display(q_simples.collect())
display(q_sem_codigos.collect())

shape: (500_000, 3)
┌────────────────┬───────────────────────┬───────┐
│ pais           ┆ nivel_desenvolvimento ┆ idade │
│ ---            ┆ ---                   ┆ ---   │
│ str            ┆ str                   ┆ i64   │
╞════════════════╪═══════════════════════╪═══════╡
│ Catar          ┆ Em desenvolvimento    ┆ 21    │
│ Estados Unidos ┆ Desenvolvido          ┆ 25    │
│ México         ┆ Em desenvolvimento    ┆ 18    │
│ Canadá         ┆ Desenvolvido          ┆ 25    │
│ Sri Lanka      ┆ Subdesenvolvido       ┆ 15    │
│ …              ┆ …                     ┆ …     │
│ Canadá         ┆ Desenvolvido          ┆ 21    │
│ Países Baixos  ┆ Desenvolvido          ┆ 19    │
│ Singapura      ┆ Desenvolvido          ┆ 17    │
│ Paquistão      ┆ Subdesenvolvido       ┆ 18    │
│ Reino Unido    ┆ Desenvolvido          ┆ 22    │
└────────────────┴───────────────────────┴───────┘

shape: (500_000, 46)
┌───────────┬───────────┬───────────┬───────────┬───┬───────────┬───────────┬───────────┬──────────┐
│ id_estuda ┆ pais      ┆ nivel_des ┆ taxa_pobr ┆ … ┆ pontuacao ┆ indice_be ┆ pontuacao ┆ pontuaca │
│ nte       ┆ ---       ┆ envolvime ┆ eza_perce ┆   ┆ _vicio_di ┆ m_estar   ┆ _risco_ac ┆ o_risco_ │
│ ---       ┆ str       ┆ nto       ┆ ntual     ┆   ┆ gital     ┆ ---       ┆ ademico   ┆ financei │
│ i64       ┆           ┆ ---       ┆ ---       ┆   ┆ ---       ┆ f64       ┆ ---       ┆ ro       │
│           ┆           ┆ str       ┆ f64       ┆   ┆ f64       ┆           ┆ f64       ┆ ---      │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆ f64      │
╞═══════════╪═══════════╪═══════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪══════════╡
│ 1         ┆ Catar     ┆ Em desenv ┆ 16.3      ┆ … ┆ 8.18      ┆ 66.66     ┆ 0.0       ┆ 26.52    │
│           ┆           ┆ olvimento ┆           ┆   ┆           ┆           ┆           ┆          │
│ 2         ┆ Estados   ┆ Desenvolv ┆ 8.75      ┆ … ┆ 22.07     ┆ 43.89     ┆ 0.0       ┆ 39.26    │
│           ┆ Unidos    ┆ ido       ┆           ┆   ┆           ┆           ┆           ┆          │
│ 3         ┆ México    ┆ Em desenv ┆ 23.64     ┆ … ┆ 12.59     ┆ 65.48     ┆ 0.0       ┆ 47.54    │
│           ┆           ┆ olvimento ┆           ┆   ┆           ┆           ┆           ┆          │
│ 4         ┆ Canadá    ┆ Desenvolv ┆ 14.51     ┆ … ┆ 8.01      ┆ 57.91     ┆ 0.0       ┆ 23.44    │
│           ┆           ┆ ido       ┆           ┆   ┆           ┆           ┆           ┆          │
│ 5         ┆ Sri Lanka ┆ Subdesenv ┆ 62.28     ┆ … ┆ 21.55     ┆ 53.69     ┆ 0.0       ┆ 47.31    │
│           ┆           ┆ olvido    ┆           ┆   ┆           ┆           ┆           ┆          │
│ …         ┆ …         ┆ …         ┆ …         ┆ … ┆ …         ┆ …         ┆ …         ┆ …        │
│ 499996    ┆ Canadá    ┆ Desenvolv ┆ 14.51     ┆ … ┆ 26.53     ┆ 52.82     ┆ 0.0       ┆ 66.51    │
│           ┆           ┆ ido       ┆           ┆   ┆           ┆           ┆           ┆          │
│ 499997    ┆ Países    ┆ Desenvolv ┆ 14.7      ┆ … ┆ 17.95     ┆ 57.49     ┆ 0.0       ┆ 42.45    │
│           ┆ Baixos    ┆ ido       ┆           ┆   ┆           ┆           ┆           ┆          │
│ 499998    ┆ Singapura ┆ Desenvolv ┆ 7.12      ┆ … ┆ 14.19     ┆ 55.45     ┆ 0.0       ┆ 31.99    │
│           ┆           ┆ ido       ┆           ┆   ┆           ┆           ┆           ┆          │
│ 499999    ┆ Paquistão ┆ Subdesenv ┆ 44.14     ┆ … ┆ 12.9      ┆ 56.26     ┆ 0.0       ┆ 33.07    │
│           ┆           ┆ olvido    ┆           ┆   ┆           ┆           ┆           ┆          │
│ 500000    ┆ Reino     ┆ Desenvolv ┆ 12.32     ┆ … ┆ 23.77     ┆ 42.46     ┆ 0.0       ┆ 57.76    │
│           ┆ Unido     ┆ ido       ┆           ┆   ┆           ┆           ┆           ┆          │
└───────────┴───────────┴───────────┴───────────┴───┴───────────┴───────────┴───────────┴──────────┘

### Condicionais
```
Criar novas colunas com base em lógica (semelhante ao IF do Excel ou CASE WHEN do SQL).
```
---

In [19]:
# Categorizar a saúde mental dos estudantes
q_categoria = inicial.with_columns(
    pl.when(pl.col("horas_sono") <= 6)
    .then(pl.lit("Baixo Sono"))
    .when(pl.col("horas_sono") < 8)
    .then(pl.lit("Médio Sono"))
    .otherwise(pl.lit("Bom Sono"))
    .alias("CATEGORIA_SONO")
)

display(q_categoria.select(["horas_sono", "CATEGORIA_SONO"]).collect())

shape: (500_000, 2)
┌────────────┬────────────────┐
│ horas_sono ┆ CATEGORIA_SONO │
│ ---        ┆ ---            │
│ f64        ┆ str            │
╞════════════╪════════════════╡
│ 7.14       ┆ Médio Sono     │
│ 4.0        ┆ Baixo Sono     │
│ 6.81       ┆ Médio Sono     │
│ 7.54       ┆ Médio Sono     │
│ 5.52       ┆ Baixo Sono     │
│ …          ┆ …              │
│ 4.86       ┆ Baixo Sono     │
│ 5.96       ┆ Baixo Sono     │
│ 5.41       ┆ Baixo Sono     │
│ 6.12       ┆ Médio Sono     │
│ 4.68       ┆ Baixo Sono     │
└────────────┴────────────────┘

In [20]:
# Partindo do LazyFrame 'q_categoria' já criado
q_analise_categoria = (
    q_categoria
    .group_by("CATEGORIA_SONO")
    .agg([
        pl.len().alias("quantidade_estudantes"),
        pl.col("horas_sono").mean().alias("media_horas_sono"),
        pl.col("horas_sono").min().alias("menor_horas_sono"),
        pl.col("horas_sono").max().alias("maior_horas_sono"),
        pl.col("horas_sono").sum().alias("total_horas_sono")
    ])
    .sort("media_horas_sono", descending=True)
)

display(q_analise_categoria.collect())

shape: (3, 6)
┌────────────────┬────────────────┬────────────────┬───────────────┬───────────────┬───────────────┐
│ CATEGORIA_SONO ┆ quantidade_est ┆ media_horas_so ┆ menor_horas_s ┆ maior_horas_s ┆ total_horas_s │
│ ---            ┆ udantes        ┆ no             ┆ ono           ┆ ono           ┆ ono           │
│ str            ┆ ---            ┆ ---            ┆ ---           ┆ ---           ┆ ---           │
│                ┆ u64            ┆ f64            ┆ f64           ┆ f64           ┆ f64           │
╞════════════════╪════════════════╪════════════════╪═══════════════╪═══════════════╪═══════════════╡
│ Bom Sono       ┆ 8455           ┆ 8.301261       ┆ 8.0           ┆ 9.0           ┆ 70187.16      │
│ Médio Sono     ┆ 244384         ┆ 6.716522       ┆ 6.01          ┆ 7.99          ┆ 1.6414e6      │
│ Baixo Sono     ┆ 247161         ┆ 5.194947       ┆ 4.0           ┆ 6.0           ┆ 1.2840e6      │
└────────────────┴────────────────┴────────────────┴───────────────┴───────────────┴───────────────┘

### Fatiamento
```
Para pegar "pedaços" dos dados. No modo Lazy, o slice é muito eficiente pois o Polars lê apenas o necessário do disco.
```
---

In [21]:
# Pegar as primeiras 10 linhas
q_head = inicial.head(10)

# Pegar da linha 100 até a 150 (offset 100, length 50)
q_meio = inicial.slice(100, 50)

display(q_head.collect())
display(q_meio.collect())

shape: (10, 48)
┌───────────┬───────────┬───────────┬───────────┬───┬───────────┬───────────┬───────────┬──────────┐
│ id_estuda ┆ pais      ┆ nivel_des ┆ taxa_pobr ┆ … ┆ pontuacao ┆ indice_be ┆ pontuacao ┆ pontuaca │
│ nte       ┆ ---       ┆ envolvime ┆ eza_perce ┆   ┆ _vicio_di ┆ m_estar   ┆ _risco_ac ┆ o_risco_ │
│ ---       ┆ str       ┆ nto       ┆ ntual     ┆   ┆ gital     ┆ ---       ┆ ademico   ┆ financei │
│ i64       ┆           ┆ ---       ┆ ---       ┆   ┆ ---       ┆ f64       ┆ ---       ┆ ro       │
│           ┆           ┆ str       ┆ f64       ┆   ┆ f64       ┆           ┆ f64       ┆ ---      │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆ f64      │
╞═══════════╪═══════════╪═══════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪══════════╡
│ 1         ┆ Catar     ┆ Em desenv ┆ 16.3      ┆ … ┆ 8.18      ┆ 66.66     ┆ 0.0       ┆ 26.52    │
│           ┆           ┆ olvimento ┆           ┆   ┆           ┆           ┆           ┆          │
│ 2         ┆ Estados   ┆ Desenvolv ┆ 8.75      ┆ … ┆ 22.07     ┆ 43.89     ┆ 0.0       ┆ 39.26    │
│           ┆ Unidos    ┆ ido       ┆           ┆   ┆           ┆           ┆           ┆          │
│ 3         ┆ México    ┆ Em desenv ┆ 23.64     ┆ … ┆ 12.59     ┆ 65.48     ┆ 0.0       ┆ 47.54    │
│           ┆           ┆ olvimento ┆           ┆   ┆           ┆           ┆           ┆          │
│ 4         ┆ Canadá    ┆ Desenvolv ┆ 14.51     ┆ … ┆ 8.01      ┆ 57.91     ┆ 0.0       ┆ 23.44    │
│           ┆           ┆ ido       ┆           ┆   ┆           ┆           ┆           ┆          │
│ 5         ┆ Sri Lanka ┆ Subdesenv ┆ 62.28     ┆ … ┆ 21.55     ┆ 53.69     ┆ 0.0       ┆ 47.31    │
│           ┆           ┆ olvido    ┆           ┆   ┆           ┆           ┆           ┆          │
│ 6         ┆ Vietnã    ┆ Em desenv ┆ 30.7      ┆ … ┆ 11.52     ┆ 57.04     ┆ 0.0       ┆ 38.46    │
│           ┆           ┆ olvimento ┆           ┆   ┆           ┆           ┆           ┆          │
│ 7         ┆ Arábia    ┆ Em desenv ┆ 18.41     ┆ … ┆ 12.8      ┆ 64.47     ┆ 0.0       ┆ 64.29    │
│           ┆ Saudita   ┆ olvimento ┆           ┆   ┆           ┆           ┆           ┆          │
│ 8         ┆ Japão     ┆ Desenvolv ┆ 6.56      ┆ … ┆ 12.97     ┆ 57.09     ┆ 0.0       ┆ 59.34    │
│           ┆           ┆ ido       ┆           ┆   ┆           ┆           ┆           ┆          │
│ 9         ┆ Arábia    ┆ Em desenv ┆ 18.41     ┆ … ┆ 9.09      ┆ 53.9      ┆ 0.0       ┆ 45.83    │
│           ┆ Saudita   ┆ olvimento ┆           ┆   ┆           ┆           ┆           ┆          │
│ 10        ┆ Alemanha  ┆ Desenvolv ┆ 10.99     ┆ … ┆ 11.75     ┆ 54.35     ┆ 0.0       ┆ 19.34    │
│           ┆           ┆ ido       ┆           ┆   ┆           ┆           ┆           ┆          │
└───────────┴───────────┴───────────┴───────────┴───┴───────────┴───────────┴───────────┴──────────┘

shape: (50, 48)
┌───────────┬───────────┬───────────┬───────────┬───┬───────────┬───────────┬───────────┬──────────┐
│ id_estuda ┆ pais      ┆ nivel_des ┆ taxa_pobr ┆ … ┆ pontuacao ┆ indice_be ┆ pontuacao ┆ pontuaca │
│ nte       ┆ ---       ┆ envolvime ┆ eza_perce ┆   ┆ _vicio_di ┆ m_estar   ┆ _risco_ac ┆ o_risco_ │
│ ---       ┆ str       ┆ nto       ┆ ntual     ┆   ┆ gital     ┆ ---       ┆ ademico   ┆ financei │
│ i64       ┆           ┆ ---       ┆ ---       ┆   ┆ ---       ┆ f64       ┆ ---       ┆ ro       │
│           ┆           ┆ str       ┆ f64       ┆   ┆ f64       ┆           ┆ f64       ┆ ---      │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆ f64      │
╞═══════════╪═══════════╪═══════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪══════════╡
│ 101       ┆ Indonésia ┆ Em desenv ┆ 27.24     ┆ … ┆ 16.78     ┆ 62.52     ┆ 0.0       ┆ 53.0     │
│           ┆           ┆ olvimento ┆           ┆   ┆           ┆           ┆           ┆          │
│ 102       ┆ Peru      ┆ Subdesenv ┆ 50.6      ┆ … ┆ 13.98     ┆ 58.89     ┆ 0.0       ┆ 33.71    │
│           ┆           ┆ olvido    ┆           ┆   ┆           ┆           ┆           ┆          │
│ 103       ┆ Turquia   ┆ Em desenv ┆ 20.82     ┆ … ┆ 9.13      ┆ 70.23     ┆ 0.0       ┆ 37.59    │
│           ┆           ┆ olvimento ┆           ┆   ┆           ┆           ┆           ┆          │
│ 104       ┆ Austrália ┆ Desenvolv ┆ 13.66     ┆ … ┆ 25.63     ┆ 45.85     ┆ 0.0       ┆ 58.25    │
│           ┆           ┆ ido       ┆           ┆   ┆           ┆           ┆           ┆          │
│ 105       ┆ Coreia do ┆ Desenvolv ┆ 5.58      ┆ … ┆ 10.32     ┆ 61.26     ┆ 0.0       ┆ 56.85    │
│           ┆ Sul       ┆ ido       ┆           ┆   ┆           ┆           ┆           ┆          │
│ …         ┆ …         ┆ …         ┆ …         ┆ … ┆ …         ┆ …         ┆ …         ┆ …        │
│ 146       ┆ Marrocos  ┆ Subdesenv ┆ 51.4      ┆ … ┆ 9.84      ┆ 75.49     ┆ 0.0       ┆ 41.02    │
│           ┆           ┆ olvido    ┆           ┆   ┆           ┆           ┆           ┆          │
│ 147       ┆ Laos      ┆ Subdesenv ┆ 54.88     ┆ … ┆ 8.06      ┆ 67.34     ┆ 0.0       ┆ 24.09    │
│           ┆           ┆ olvido    ┆           ┆   ┆           ┆           ┆           ┆          │
│ 148       ┆ Emirados  ┆ Em desenv ┆ 27.15     ┆ … ┆ 20.71     ┆ 49.84     ┆ 0.0       ┆ 47.64    │
│           ┆ Árabes    ┆ olvimento ┆           ┆   ┆           ┆           ┆           ┆          │
│           ┆ Unidos    ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ 149       ┆ Omã       ┆ Em desenv ┆ 34.31     ┆ … ┆ 14.47     ┆ 54.93     ┆ 0.0       ┆ 50.66    │
│           ┆           ┆ olvimento ┆           ┆   ┆           ┆           ┆           ┆          │
│ 150       ┆ Catar     ┆ Em desenv ┆ 16.3      ┆ … ┆ 9.87      ┆ 50.9      ┆ 0.0       ┆ 41.71    │
│           ┆           ┆ olvimento ┆           ┆   ┆           ┆           ┆           ┆          │
└───────────┴───────────┴───────────┴───────────┴───┴───────────┴───────────┴───────────┴──────────┘

In [22]:
# Recorte de linhas específicas (ex: linha 0, 10 e 50)
q_recorte_indices = (
    inicial
    .with_row_index("id_linha")  # Cria uma coluna temporária com o número da linha
    .filter(pl.col("id_linha").is_in([0, 10, 50])) # Filtra pelos números desejados
    .select(["pais", "nivel_desenvolvimento"]) # Seleciona as colunas
)

display(q_recorte_indices.collect())

shape: (3, 2)
┌───────────┬───────────────────────┐
│ pais      ┆ nivel_desenvolvimento │
│ ---       ┆ ---                   │
│ str       ┆ str                   │
╞═══════════╪═══════════════════════╡
│ Catar     ┆ Em desenvolvimento    │
│ Dinamarca ┆ Desenvolvido          │
│ Tanzânia  ┆ Subdesenvolvido       │
└───────────┴───────────────────────┘

### Agrupamento Avançado (group_by + agg)
---

In [40]:
q_stats_mun = (
    inicial.group_by("nivel_escolaridade")
    .agg([
        pl.len().alias("total_estudantes"),  # Contagem rápida
        pl.col("horas_redes_sociais").sum().alias("horas_redes_sociais_total"),  # Soma
        pl.col("taxa_frequencia_aulas").mean().alias("media_frequencia"), # Média
        pl.col("capacidade_atencao_minutos").mean().alias("media_atencao"),  # Média
        
    ])
    .sort("horas_redes_sociais_total", descending=True)
)

display(q_stats_mun.collect())

shape: (6, 5)
┌────────────────────┬──────────────────┬───────────────────────┬──────────────────┬───────────────┐
│ nivel_escolaridade ┆ total_estudantes ┆ horas_redes_sociais_t ┆ media_frequencia ┆ media_atencao │
│ ---                ┆ ---              ┆ otal                  ┆ ---              ┆ ---           │
│ str                ┆ u64              ┆ ---                   ┆ f64              ┆ f64           │
│                    ┆                  ┆ f64                   ┆                  ┆               │
╞════════════════════╪══════════════════╪═══════════════════════╪══════════════════╪═══════════════╡
│ Ensino básico      ┆ 186521           ┆ 654223.44             ┆ 89.905849        ┆ 52.840769     │
│ Técnico            ┆ 116634           ┆ 402711.31             ┆ 90.893909        ┆ 53.823644     │
│ Graduação          ┆ 104759           ┆ 330579.72             ┆ 93.059642        ┆ 55.951182     │
│ Evasão             ┆ 60828            ┆ 203890.1              ┆ 87.378255        ┆ 50.424091     │
│ Pós-graduação      ┆ 27825            ┆ 79401.73              ┆ 94.226614        ┆ 57.085091     │
│ Doutorado          ┆ 3433             ┆ 9588.29               ┆ 95.813816        ┆ 58.271107     │
└────────────────────┴──────────────────┴───────────────────────┴──────────────────┴───────────────┘

### StringCache e Otimização de CPU
---

In [ ]:
print("=== TESTE 1: Processamento SEM StringCache ===")
start_1 = time.time()

q_sem_cache = (
    pl.scan_parquet("estudantes.parquet")
    .group_by(["pais", "nivel_desenvolvimento"]) 
    .agg([
        pl.col("pontuacao_vicio_digital").mean().alias("media"),
        pl.col("pontuacao_vicio_digital").std().alias("desvio")
    ])
    .sort("media", descending=True)
)

df_1 = q_sem_cache.collect()
end_1 = time.time()

tempo_sem = end_1 - start_1

print(f"Tempo SEM Cache: {tempo_sem:.4f} segundos")
print(f"Uso de memória estimado (coluna pais): {df_1['pais'].estimated_size()} bytes\n")

=== TESTE 1: Processamento SEM StringCache ===
Tempo SEM Cache: 0.0266 segundos
Uso de memória estimado (coluna pais): 428 bytes

In [48]:
print("=== TESTE 2: Processamento COM StringCache ===")
# O StringCache funciona como um contexto (with)
with pl.StringCache():
    start_2 = time.time()

    q_com_cache = (
    pl.scan_parquet("estudantes.parquet")
    .group_by(["pais", "nivel_desenvolvimento"]) 
        .agg([
            pl.col("pontuacao_vicio_digital").mean().alias("media"),
            pl.col("pontuacao_vicio_digital").std().alias("desvio")
        ])
        .sort("media", descending=True)
    )

df_2 = q_com_cache.collect() # Ação!
end_2 = time.time()

tempo_com = end_2 - start_2

print(f"Tempo COM Cache: {tempo_com:.4f} segundos")
print(f"Uso de memória estimado (coluna pais): {df_2['pais'].estimated_size()} bytes\n")

=== TESTE 2: Processamento COM StringCache ===
Tempo COM Cache: 0.0257 segundos
Uso de memória estimado (coluna pais): 428 bytes

C:\Users\Indi\AppData\Local\Temp\ipykernel_504\3440561067.py:3: DeprecationWarning: the string cache has been replaced by pl.Categories
  with pl.StringCache():