# Análise Estatística
```
Tema: Impacto das redes sociais na saúde e notas dos alunos
```
---

In [2]:
import polars as pl
import time

In [3]:
inicial = (
    pl.scan_parquet("estudantes.parquet"))

display(inicial.collect())

shape: (500_000, 48)
┌───────────┬───────────┬───────────┬───────────┬───┬───────────┬───────────┬───────────┬──────────┐
│ id_estuda ┆ pais      ┆ nivel_des ┆ taxa_pobr ┆ … ┆ pontuacao ┆ indice_be ┆ pontuacao ┆ pontuaca │
│ nte       ┆ ---       ┆ envolvime ┆ eza_perce ┆   ┆ _vicio_di ┆ m_estar   ┆ _risco_ac ┆ o_risco_ │
│ ---       ┆ str       ┆ nto       ┆ ntual     ┆   ┆ gital     ┆ ---       ┆ ademico   ┆ financei │
│ i64       ┆           ┆ ---       ┆ ---       ┆   ┆ ---       ┆ f64       ┆ ---       ┆ ro       │
│           ┆           ┆ str       ┆ f64       ┆   ┆ f64       ┆           ┆ f64       ┆ ---      │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆ f64      │
╞═══════════╪═══════════╪═══════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪══════════╡
│ 1         ┆ Catar     ┆ Em desenv ┆ 16.3      ┆ … ┆ 8.18      ┆ 66.66     ┆ 0.0       ┆ 26.52    │
│           ┆           ┆ olvimento ┆           ┆   ┆           ┆           ┆           ┆          │
│ 2         ┆ Estados   ┆ Desenvolv ┆ 8.75      ┆ … ┆ 22.07     ┆ 43.89     ┆ 0.0       ┆ 39.26    │
│           ┆ Unidos    ┆ ido       ┆           ┆   ┆           ┆           ┆           ┆          │
│ 3         ┆ México    ┆ Em desenv ┆ 23.64     ┆ … ┆ 12.59     ┆ 65.48     ┆ 0.0       ┆ 47.54    │
│           ┆           ┆ olvimento ┆           ┆   ┆           ┆           ┆           ┆          │
│ 4         ┆ Canadá    ┆ Desenvolv ┆ 14.51     ┆ … ┆ 8.01      ┆ 57.91     ┆ 0.0       ┆ 23.44    │
│           ┆           ┆ ido       ┆           ┆   ┆           ┆           ┆           ┆          │
│ 5         ┆ Sri Lanka ┆ Subdesenv ┆ 62.28     ┆ … ┆ 21.55     ┆ 53.69     ┆ 0.0       ┆ 47.31    │
│           ┆           ┆ olvido    ┆           ┆   ┆           ┆           ┆           ┆          │
│ …         ┆ …         ┆ …         ┆ …         ┆ … ┆ …         ┆ …         ┆ …         ┆ …        │
│ 499996    ┆ Canadá    ┆ Desenvolv ┆ 14.51     ┆ … ┆ 26.53     ┆ 52.82     ┆ 0.0       ┆ 66.51    │
│           ┆           ┆ ido       ┆           ┆   ┆           ┆           ┆           ┆          │
│ 499997    ┆ Países    ┆ Desenvolv ┆ 14.7      ┆ … ┆ 17.95     ┆ 57.49     ┆ 0.0       ┆ 42.45    │
│           ┆ Baixos    ┆ ido       ┆           ┆   ┆           ┆           ┆           ┆          │
│ 499998    ┆ Singapura ┆ Desenvolv ┆ 7.12      ┆ … ┆ 14.19     ┆ 55.45     ┆ 0.0       ┆ 31.99    │
│           ┆           ┆ ido       ┆           ┆   ┆           ┆           ┆           ┆          │
│ 499999    ┆ Paquistão ┆ Subdesenv ┆ 44.14     ┆ … ┆ 12.9      ┆ 56.26     ┆ 0.0       ┆ 33.07    │
│           ┆           ┆ olvido    ┆           ┆   ┆           ┆           ┆           ┆          │
│ 500000    ┆ Reino     ┆ Desenvolv ┆ 12.32     ┆ … ┆ 23.77     ┆ 42.46     ┆ 0.0       ┆ 57.76    │
│           ┆ Unido     ┆ ido       ┆           ┆   ┆           ┆           ┆           ┆          │
└───────────┴───────────┴───────────┴───────────┴───┴───────────┴───────────┴───────────┴──────────┘

### Filtro alto uso de redes (>5h) e pouco sono (<=6h).
---

In [14]:
# Filtro composto (E): muito tempo em redes sociais e pouco sono
q_risco = inicial.filter(
    (pl.col("horas_redes_sociais") > 5) & (pl.col("horas_sono") <= 6)
)

total = inicial.select(pl.len()).collect().item()
n_risco = q_risco.select(pl.len()).collect().item()

print(f"Filtro alto uso de redes (>5h) e pouco sono (<=6h): {n_risco:,} estudantes ({n_risco/total:.1%})")
display(q_risco.collect())

Filtro alto uso de redes (>5h) e pouco sono (<=6h): 52,675 estudantes (10.5%)

shape: (52_675, 48)
┌───────────┬───────────┬───────────┬───────────┬───┬───────────┬───────────┬───────────┬──────────┐
│ id_estuda ┆ pais      ┆ nivel_des ┆ taxa_pobr ┆ … ┆ pontuacao ┆ indice_be ┆ pontuacao ┆ pontuaca │
│ nte       ┆ ---       ┆ envolvime ┆ eza_perce ┆   ┆ _vicio_di ┆ m_estar   ┆ _risco_ac ┆ o_risco_ │
│ ---       ┆ str       ┆ nto       ┆ ntual     ┆   ┆ gital     ┆ ---       ┆ ademico   ┆ financei │
│ i64       ┆           ┆ ---       ┆ ---       ┆   ┆ ---       ┆ f64       ┆ ---       ┆ ro       │
│           ┆           ┆ str       ┆ f64       ┆   ┆ f64       ┆           ┆ f64       ┆ ---      │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆ f64      │
╞═══════════╪═══════════╪═══════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪══════════╡
│ 2         ┆ Estados   ┆ Desenvolv ┆ 8.75      ┆ … ┆ 22.07     ┆ 43.89     ┆ 0.0       ┆ 39.26    │
│           ┆ Unidos    ┆ ido       ┆           ┆   ┆           ┆           ┆           ┆          │
│ 5         ┆ Sri Lanka ┆ Subdesenv ┆ 62.28     ┆ … ┆ 21.55     ┆ 53.69     ┆ 0.0       ┆ 47.31    │
│           ┆           ┆ olvido    ┆           ┆   ┆           ┆           ┆           ┆          │
│ 19        ┆ Dinamarca ┆ Desenvolv ┆ 5.21      ┆ … ┆ 22.82     ┆ 37.9      ┆ 0.0       ┆ 56.26    │
│           ┆           ┆ ido       ┆           ┆   ┆           ┆           ┆           ┆          │
│ 21        ┆ China     ┆ Em desenv ┆ 18.67     ┆ … ┆ 23.13     ┆ 36.18     ┆ 0.0       ┆ 59.14    │
│           ┆           ┆ olvimento ┆           ┆   ┆           ┆           ┆           ┆          │
│ 26        ┆ Polônia   ┆ Em desenv ┆ 26.85     ┆ … ┆ 28.85     ┆ 26.2      ┆ 3.23      ┆ 58.63    │
│           ┆           ┆ olvimento ┆           ┆   ┆           ┆           ┆           ┆          │
│ …         ┆ …         ┆ …         ┆ …         ┆ … ┆ …         ┆ …         ┆ …         ┆ …        │
│ 499964    ┆ Suíça     ┆ Desenvolv ┆ 13.32     ┆ … ┆ 30.49     ┆ 46.52     ┆ 0.0       ┆ 77.56    │
│           ┆           ┆ ido       ┆           ┆   ┆           ┆           ┆           ┆          │
│ 499966    ┆ Arábia    ┆ Em desenv ┆ 18.41     ┆ … ┆ 22.71     ┆ 60.99     ┆ 0.0       ┆ 61.38    │
│           ┆ Saudita   ┆ olvimento ┆           ┆   ┆           ┆           ┆           ┆          │
│ 499968    ┆ Japão     ┆ Desenvolv ┆ 6.56      ┆ … ┆ 18.77     ┆ 46.61     ┆ 0.0       ┆ 52.38    │
│           ┆           ┆ ido       ┆           ┆   ┆           ┆           ┆           ┆          │
│ 499983    ┆ Kuwait    ┆ Em desenv ┆ 33.98     ┆ … ┆ 23.83     ┆ 31.66     ┆ 0.0       ┆ 67.98    │
│           ┆           ┆ olvimento ┆           ┆   ┆           ┆           ┆           ┆          │
│ 499996    ┆ Canadá    ┆ Desenvolv ┆ 14.51     ┆ … ┆ 26.53     ┆ 52.82     ┆ 0.0       ┆ 66.51    │
│           ┆           ┆ ido       ┆           ┆   ┆           ┆           ┆           ┆          │
└───────────┴───────────┴───────────┴───────────┴───┴───────────┴───────────┴───────────┴──────────┘

```
Análise: 10.5% dos estudantes da amostra, usam as redes por 5h ou mais e possuem 6h ou menos de sono.
```

### Filtro países desenvolvidos vs demais países.
---

In [15]:
# Filtro com lista (IS IN): estudantes de países desenvolvidos x demais
q_desenvolvidos = inicial.filter(pl.col("nivel_desenvolvimento").is_in(["Desenvolvido"]))
q_demais = inicial.filter(pl.col("nivel_desenvolvimento").is_in(["Em desenvolvimento", "Subdesenvolvido"]))

print(f"Filtro países desenvolvidos: {q_desenvolvidos.select(pl.len()).collect().item():,}")
display(q_desenvolvidos.collect())
print(f"Filtro demais países: {q_demais.select(pl.len()).collect().item():,}")
display(q_demais.collect())

Filtro países desenvolvidos: 149,548

shape: (149_548, 48)
┌───────────┬───────────┬───────────┬───────────┬───┬───────────┬───────────┬───────────┬──────────┐
│ id_estuda ┆ pais      ┆ nivel_des ┆ taxa_pobr ┆ … ┆ pontuacao ┆ indice_be ┆ pontuacao ┆ pontuaca │
│ nte       ┆ ---       ┆ envolvime ┆ eza_perce ┆   ┆ _vicio_di ┆ m_estar   ┆ _risco_ac ┆ o_risco_ │
│ ---       ┆ str       ┆ nto       ┆ ntual     ┆   ┆ gital     ┆ ---       ┆ ademico   ┆ financei │
│ i64       ┆           ┆ ---       ┆ ---       ┆   ┆ ---       ┆ f64       ┆ ---       ┆ ro       │
│           ┆           ┆ str       ┆ f64       ┆   ┆ f64       ┆           ┆ f64       ┆ ---      │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆ f64      │
╞═══════════╪═══════════╪═══════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪══════════╡
│ 2         ┆ Estados   ┆ Desenvolv ┆ 8.75      ┆ … ┆ 22.07     ┆ 43.89     ┆ 0.0       ┆ 39.26    │
│           ┆ Unidos    ┆ ido       ┆           ┆   ┆           ┆           ┆           ┆          │
│ 4         ┆ Canadá    ┆ Desenvolv ┆ 14.51     ┆ … ┆ 8.01      ┆ 57.91     ┆ 0.0       ┆ 23.44    │
│           ┆           ┆ ido       ┆           ┆   ┆           ┆           ┆           ┆          │
│ 8         ┆ Japão     ┆ Desenvolv ┆ 6.56      ┆ … ┆ 12.97     ┆ 57.09     ┆ 0.0       ┆ 59.34    │
│           ┆           ┆ ido       ┆           ┆   ┆           ┆           ┆           ┆          │
│ 10        ┆ Alemanha  ┆ Desenvolv ┆ 10.99     ┆ … ┆ 11.75     ┆ 54.35     ┆ 0.0       ┆ 19.34    │
│           ┆           ┆ ido       ┆           ┆   ┆           ┆           ┆           ┆          │
│ 11        ┆ Dinamarca ┆ Desenvolv ┆ 5.21      ┆ … ┆ 12.07     ┆ 62.98     ┆ 0.0       ┆ 42.27    │
│           ┆           ┆ ido       ┆           ┆   ┆           ┆           ┆           ┆          │
│ …         ┆ …         ┆ …         ┆ …         ┆ … ┆ …         ┆ …         ┆ …         ┆ …        │
│ 499995    ┆ Suécia    ┆ Desenvolv ┆ 11.01     ┆ … ┆ 19.76     ┆ 47.73     ┆ 0.0       ┆ 38.16    │
│           ┆           ┆ ido       ┆           ┆   ┆           ┆           ┆           ┆          │
│ 499996    ┆ Canadá    ┆ Desenvolv ┆ 14.51     ┆ … ┆ 26.53     ┆ 52.82     ┆ 0.0       ┆ 66.51    │
│           ┆           ┆ ido       ┆           ┆   ┆           ┆           ┆           ┆          │
│ 499997    ┆ Países    ┆ Desenvolv ┆ 14.7      ┆ … ┆ 17.95     ┆ 57.49     ┆ 0.0       ┆ 42.45    │
│           ┆ Baixos    ┆ ido       ┆           ┆   ┆           ┆           ┆           ┆          │
│ 499998    ┆ Singapura ┆ Desenvolv ┆ 7.12      ┆ … ┆ 14.19     ┆ 55.45     ┆ 0.0       ┆ 31.99    │
│           ┆           ┆ ido       ┆           ┆   ┆           ┆           ┆           ┆          │
│ 500000    ┆ Reino     ┆ Desenvolv ┆ 12.32     ┆ … ┆ 23.77     ┆ 42.46     ┆ 0.0       ┆ 57.76    │
│           ┆ Unido     ┆ ido       ┆           ┆   ┆           ┆           ┆           ┆          │
└───────────┴───────────┴───────────┴───────────┴───┴───────────┴───────────┴───────────┴──────────┘

Filtro demais países: 350,452

shape: (350_452, 48)
┌───────────┬───────────┬───────────┬───────────┬───┬───────────┬───────────┬───────────┬──────────┐
│ id_estuda ┆ pais      ┆ nivel_des ┆ taxa_pobr ┆ … ┆ pontuacao ┆ indice_be ┆ pontuacao ┆ pontuaca │
│ nte       ┆ ---       ┆ envolvime ┆ eza_perce ┆   ┆ _vicio_di ┆ m_estar   ┆ _risco_ac ┆ o_risco_ │
│ ---       ┆ str       ┆ nto       ┆ ntual     ┆   ┆ gital     ┆ ---       ┆ ademico   ┆ financei │
│ i64       ┆           ┆ ---       ┆ ---       ┆   ┆ ---       ┆ f64       ┆ ---       ┆ ro       │
│           ┆           ┆ str       ┆ f64       ┆   ┆ f64       ┆           ┆ f64       ┆ ---      │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆ f64      │
╞═══════════╪═══════════╪═══════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪══════════╡
│ 1         ┆ Catar     ┆ Em desenv ┆ 16.3      ┆ … ┆ 8.18      ┆ 66.66     ┆ 0.0       ┆ 26.52    │
│           ┆           ┆ olvimento ┆           ┆   ┆           ┆           ┆           ┆          │
│ 3         ┆ México    ┆ Em desenv ┆ 23.64     ┆ … ┆ 12.59     ┆ 65.48     ┆ 0.0       ┆ 47.54    │
│           ┆           ┆ olvimento ┆           ┆   ┆           ┆           ┆           ┆          │
│ 5         ┆ Sri Lanka ┆ Subdesenv ┆ 62.28     ┆ … ┆ 21.55     ┆ 53.69     ┆ 0.0       ┆ 47.31    │
│           ┆           ┆ olvido    ┆           ┆   ┆           ┆           ┆           ┆          │
│ 6         ┆ Vietnã    ┆ Em desenv ┆ 30.7      ┆ … ┆ 11.52     ┆ 57.04     ┆ 0.0       ┆ 38.46    │
│           ┆           ┆ olvimento ┆           ┆   ┆           ┆           ┆           ┆          │
│ 7         ┆ Arábia    ┆ Em desenv ┆ 18.41     ┆ … ┆ 12.8      ┆ 64.47     ┆ 0.0       ┆ 64.29    │
│           ┆ Saudita   ┆ olvimento ┆           ┆   ┆           ┆           ┆           ┆          │
│ …         ┆ …         ┆ …         ┆ …         ┆ … ┆ …         ┆ …         ┆ …         ┆ …        │
│ 499988    ┆ Vietnã    ┆ Em desenv ┆ 30.7      ┆ … ┆ 10.21     ┆ 58.01     ┆ 0.0       ┆ 53.97    │
│           ┆           ┆ olvimento ┆           ┆   ┆           ┆           ┆           ┆          │
│ 499989    ┆ Turquia   ┆ Em desenv ┆ 20.82     ┆ … ┆ 8.44      ┆ 75.58     ┆ 0.0       ┆ 41.68    │
│           ┆           ┆ olvimento ┆           ┆   ┆           ┆           ┆           ┆          │
│ 499991    ┆ Arábia    ┆ Em desenv ┆ 18.41     ┆ … ┆ 14.61     ┆ 44.75     ┆ 0.0       ┆ 35.89    │
│           ┆ Saudita   ┆ olvimento ┆           ┆   ┆           ┆           ┆           ┆          │
│ 499994    ┆ México    ┆ Em desenv ┆ 23.64     ┆ … ┆ 9.5       ┆ 55.39     ┆ 0.0       ┆ 40.54    │
│           ┆           ┆ olvimento ┆           ┆   ┆           ┆           ┆           ┆          │
│ 499999    ┆ Paquistão ┆ Subdesenv ┆ 44.14     ┆ … ┆ 12.9      ┆ 56.26     ┆ 0.0       ┆ 33.07    │
│           ┆           ┆ olvido    ┆           ┆   ┆           ┆           ┆           ┆          │
└───────────┴───────────┴───────────┴───────────┴───┴───────────┴───────────┴───────────┴──────────┘

```
Análise: 149.548 estudantes da amostra, residem em países desenvolvidos, enquanto 350.452 dos estudantes residem em países subdesenvolvidos ou em desenvolvimento.
```

### Somente colunas redes sociais, bem-estar e capacidade de atenção.
---

In [24]:
# Selecionar apenas as colunas do tema (redes sociais, bem-estar e capacidade de atenção)
cols_tema = ["id_estudante","horas_redes_sociais", "indice_bem_estar", "capacidade_atencao_minutos"]
q_tema = inicial.select(list(dict.fromkeys(cols_tema)))

# .drop() remove as colunas listadas
q_sem_infra = inicial.drop(["indice_infraestrutura_internet", "velocidade_media_internet_mbps"])

display(q_tema.head().collect())
display(q_sem_infra.head().collect())
print("q_tema:", q_tema.collect_schema().len(), "colunas | q_sem_infra:", q_sem_infra.collect_schema().len(), "colunas")

shape: (5, 4)
┌──────────────┬─────────────────────┬──────────────────┬────────────────────────────┐
│ id_estudante ┆ horas_redes_sociais ┆ indice_bem_estar ┆ capacidade_atencao_minutos │
│ ---          ┆ ---                 ┆ ---              ┆ ---                        │
│ i64          ┆ f64                 ┆ f64              ┆ f64                        │
╞══════════════╪═════════════════════╪══════════════════╪════════════════════════════╡
│ 1            ┆ 1.1                 ┆ 66.66            ┆ 57.55                      │
│ 2            ┆ 5.61                ┆ 43.89            ┆ 51.31                      │
│ 3            ┆ 2.2                 ┆ 65.48            ┆ 55.84                      │
│ 4            ┆ 2.25                ┆ 57.91            ┆ 58.03                      │
│ 5            ┆ 5.38                ┆ 53.69            ┆ 60.0                       │
└──────────────┴─────────────────────┴──────────────────┴────────────────────────────┘

shape: (5, 46)
┌───────────┬───────────┬───────────┬───────────┬───┬───────────┬───────────┬───────────┬──────────┐
│ id_estuda ┆ pais      ┆ nivel_des ┆ taxa_pobr ┆ … ┆ pontuacao ┆ indice_be ┆ pontuacao ┆ pontuaca │
│ nte       ┆ ---       ┆ envolvime ┆ eza_perce ┆   ┆ _vicio_di ┆ m_estar   ┆ _risco_ac ┆ o_risco_ │
│ ---       ┆ str       ┆ nto       ┆ ntual     ┆   ┆ gital     ┆ ---       ┆ ademico   ┆ financei │
│ i64       ┆           ┆ ---       ┆ ---       ┆   ┆ ---       ┆ f64       ┆ ---       ┆ ro       │
│           ┆           ┆ str       ┆ f64       ┆   ┆ f64       ┆           ┆ f64       ┆ ---      │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆ f64      │
╞═══════════╪═══════════╪═══════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪══════════╡
│ 1         ┆ Catar     ┆ Em desenv ┆ 16.3      ┆ … ┆ 8.18      ┆ 66.66     ┆ 0.0       ┆ 26.52    │
│           ┆           ┆ olvimento ┆           ┆   ┆           ┆           ┆           ┆          │
│ 2         ┆ Estados   ┆ Desenvolv ┆ 8.75      ┆ … ┆ 22.07     ┆ 43.89     ┆ 0.0       ┆ 39.26    │
│           ┆ Unidos    ┆ ido       ┆           ┆   ┆           ┆           ┆           ┆          │
│ 3         ┆ México    ┆ Em desenv ┆ 23.64     ┆ … ┆ 12.59     ┆ 65.48     ┆ 0.0       ┆ 47.54    │
│           ┆           ┆ olvimento ┆           ┆   ┆           ┆           ┆           ┆          │
│ 4         ┆ Canadá    ┆ Desenvolv ┆ 14.51     ┆ … ┆ 8.01      ┆ 57.91     ┆ 0.0       ┆ 23.44    │
│           ┆           ┆ ido       ┆           ┆   ┆           ┆           ┆           ┆          │
│ 5         ┆ Sri Lanka ┆ Subdesenv ┆ 62.28     ┆ … ┆ 21.55     ┆ 53.69     ┆ 0.0       ┆ 47.31    │
│           ┆           ┆ olvido    ┆           ┆   ┆           ┆           ┆           ┆          │
└───────────┴───────────┴───────────┴───────────┴───┴───────────┴───────────┴───────────┴──────────┘

q_tema: 4 colunas | q_sem_infra: 46 colunas

```
Análise: no recorte acima conseguimos visualizar com precisão os primeiros 5 estudantes.
```

### Categorização de horas de sono e uso de redes sociais.
---

In [30]:
# Categorias de sono, uso de redes sociais
exprs = [
    pl.when(pl.col("horas_sono") <= 6).then(pl.lit("1-Baixo (≤6h)"))
      .when(pl.col("horas_sono") < 8).then(pl.lit("2-Médio (6-8h)"))
      .otherwise(pl.lit("3-Bom (≥8h)")).alias("categoria_sono"),

    pl.when(pl.col("horas_redes_sociais") < 2).then(pl.lit("1-Baixo (<2h)"))
      .when(pl.col("horas_redes_sociais") < 5).then(pl.lit("2-Moderado (2-5h)"))
      .otherwise(pl.lit("3-Alto (≥5h)")).alias("categoria_redes"),
]

q_cat = inicial.with_columns(exprs)
cols_cat = [c for c in ["horas_sono", "categoria_sono", "horas_redes_sociais", "categoria_redes"] if c]
display(q_cat.select(cols_cat).head(10).collect())

shape: (10, 4)
┌────────────┬────────────────┬─────────────────────┬───────────────────┐
│ horas_sono ┆ categoria_sono ┆ horas_redes_sociais ┆ categoria_redes   │
│ ---        ┆ ---            ┆ ---                 ┆ ---               │
│ f64        ┆ str            ┆ f64                 ┆ str               │
╞════════════╪════════════════╪═════════════════════╪═══════════════════╡
│ 7.14       ┆ 2-Médio (6-8h) ┆ 1.1                 ┆ 1-Baixo (<2h)     │
│ 4.0        ┆ 1-Baixo (≤6h)  ┆ 5.61                ┆ 3-Alto (≥5h)      │
│ 6.81       ┆ 2-Médio (6-8h) ┆ 2.2                 ┆ 2-Moderado (2-5h) │
│ 7.54       ┆ 2-Médio (6-8h) ┆ 2.25                ┆ 2-Moderado (2-5h) │
│ 5.52       ┆ 1-Baixo (≤6h)  ┆ 5.38                ┆ 3-Alto (≥5h)      │
│ 6.19       ┆ 2-Médio (6-8h) ┆ 3.03                ┆ 2-Moderado (2-5h) │
│ 6.72       ┆ 2-Médio (6-8h) ┆ 3.49                ┆ 2-Moderado (2-5h) │
│ 5.61       ┆ 1-Baixo (≤6h)  ┆ 4.12                ┆ 2-Moderado (2-5h) │
│ 5.99       ┆ 1-Baixo (≤6h)  ┆ 3.89                ┆ 2-Moderado (2-5h) │
│ 5.12       ┆ 1-Baixo (≤6h)  ┆ 3.04                ┆ 2-Moderado (2-5h) │
└────────────┴────────────────┴─────────────────────┴───────────────────┘

```
Análise: categorização de sono e uso de redes baseado na quantidade de horas.
```

### Pequenas amostras das primeiras 10 linhas e também da linhas 100 até a linha 150.
---

In [19]:
q_head = inicial.head(10)          # primeiras 10 linhas
q_meio = inicial.slice(100, 50)    # offset 100, 50 linhas

display(q_head.collect())
display(q_meio.collect())

shape: (10, 48)
┌───────────┬───────────┬───────────┬───────────┬───┬───────────┬───────────┬───────────┬──────────┐
│ id_estuda ┆ pais      ┆ nivel_des ┆ taxa_pobr ┆ … ┆ pontuacao ┆ indice_be ┆ pontuacao ┆ pontuaca │
│ nte       ┆ ---       ┆ envolvime ┆ eza_perce ┆   ┆ _vicio_di ┆ m_estar   ┆ _risco_ac ┆ o_risco_ │
│ ---       ┆ str       ┆ nto       ┆ ntual     ┆   ┆ gital     ┆ ---       ┆ ademico   ┆ financei │
│ i64       ┆           ┆ ---       ┆ ---       ┆   ┆ ---       ┆ f64       ┆ ---       ┆ ro       │
│           ┆           ┆ str       ┆ f64       ┆   ┆ f64       ┆           ┆ f64       ┆ ---      │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆ f64      │
╞═══════════╪═══════════╪═══════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪══════════╡
│ 1         ┆ Catar     ┆ Em desenv ┆ 16.3      ┆ … ┆ 8.18      ┆ 66.66     ┆ 0.0       ┆ 26.52    │
│           ┆           ┆ olvimento ┆           ┆   ┆           ┆           ┆           ┆          │
│ 2         ┆ Estados   ┆ Desenvolv ┆ 8.75      ┆ … ┆ 22.07     ┆ 43.89     ┆ 0.0       ┆ 39.26    │
│           ┆ Unidos    ┆ ido       ┆           ┆   ┆           ┆           ┆           ┆          │
│ 3         ┆ México    ┆ Em desenv ┆ 23.64     ┆ … ┆ 12.59     ┆ 65.48     ┆ 0.0       ┆ 47.54    │
│           ┆           ┆ olvimento ┆           ┆   ┆           ┆           ┆           ┆          │
│ 4         ┆ Canadá    ┆ Desenvolv ┆ 14.51     ┆ … ┆ 8.01      ┆ 57.91     ┆ 0.0       ┆ 23.44    │
│           ┆           ┆ ido       ┆           ┆   ┆           ┆           ┆           ┆          │
│ 5         ┆ Sri Lanka ┆ Subdesenv ┆ 62.28     ┆ … ┆ 21.55     ┆ 53.69     ┆ 0.0       ┆ 47.31    │
│           ┆           ┆ olvido    ┆           ┆   ┆           ┆           ┆           ┆          │
│ 6         ┆ Vietnã    ┆ Em desenv ┆ 30.7      ┆ … ┆ 11.52     ┆ 57.04     ┆ 0.0       ┆ 38.46    │
│           ┆           ┆ olvimento ┆           ┆   ┆           ┆           ┆           ┆          │
│ 7         ┆ Arábia    ┆ Em desenv ┆ 18.41     ┆ … ┆ 12.8      ┆ 64.47     ┆ 0.0       ┆ 64.29    │
│           ┆ Saudita   ┆ olvimento ┆           ┆   ┆           ┆           ┆           ┆          │
│ 8         ┆ Japão     ┆ Desenvolv ┆ 6.56      ┆ … ┆ 12.97     ┆ 57.09     ┆ 0.0       ┆ 59.34    │
│           ┆           ┆ ido       ┆           ┆   ┆           ┆           ┆           ┆          │
│ 9         ┆ Arábia    ┆ Em desenv ┆ 18.41     ┆ … ┆ 9.09      ┆ 53.9      ┆ 0.0       ┆ 45.83    │
│           ┆ Saudita   ┆ olvimento ┆           ┆   ┆           ┆           ┆           ┆          │
│ 10        ┆ Alemanha  ┆ Desenvolv ┆ 10.99     ┆ … ┆ 11.75     ┆ 54.35     ┆ 0.0       ┆ 19.34    │
│           ┆           ┆ ido       ┆           ┆   ┆           ┆           ┆           ┆          │
└───────────┴───────────┴───────────┴───────────┴───┴───────────┴───────────┴───────────┴──────────┘

shape: (50, 48)
┌───────────┬───────────┬───────────┬───────────┬───┬───────────┬───────────┬───────────┬──────────┐
│ id_estuda ┆ pais      ┆ nivel_des ┆ taxa_pobr ┆ … ┆ pontuacao ┆ indice_be ┆ pontuacao ┆ pontuaca │
│ nte       ┆ ---       ┆ envolvime ┆ eza_perce ┆   ┆ _vicio_di ┆ m_estar   ┆ _risco_ac ┆ o_risco_ │
│ ---       ┆ str       ┆ nto       ┆ ntual     ┆   ┆ gital     ┆ ---       ┆ ademico   ┆ financei │
│ i64       ┆           ┆ ---       ┆ ---       ┆   ┆ ---       ┆ f64       ┆ ---       ┆ ro       │
│           ┆           ┆ str       ┆ f64       ┆   ┆ f64       ┆           ┆ f64       ┆ ---      │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆ f64      │
╞═══════════╪═══════════╪═══════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪══════════╡
│ 101       ┆ Indonésia ┆ Em desenv ┆ 27.24     ┆ … ┆ 16.78     ┆ 62.52     ┆ 0.0       ┆ 53.0     │
│           ┆           ┆ olvimento ┆           ┆   ┆           ┆           ┆           ┆          │
│ 102       ┆ Peru      ┆ Subdesenv ┆ 50.6      ┆ … ┆ 13.98     ┆ 58.89     ┆ 0.0       ┆ 33.71    │
│           ┆           ┆ olvido    ┆           ┆   ┆           ┆           ┆           ┆          │
│ 103       ┆ Turquia   ┆ Em desenv ┆ 20.82     ┆ … ┆ 9.13      ┆ 70.23     ┆ 0.0       ┆ 37.59    │
│           ┆           ┆ olvimento ┆           ┆   ┆           ┆           ┆           ┆          │
│ 104       ┆ Austrália ┆ Desenvolv ┆ 13.66     ┆ … ┆ 25.63     ┆ 45.85     ┆ 0.0       ┆ 58.25    │
│           ┆           ┆ ido       ┆           ┆   ┆           ┆           ┆           ┆          │
│ 105       ┆ Coreia do ┆ Desenvolv ┆ 5.58      ┆ … ┆ 10.32     ┆ 61.26     ┆ 0.0       ┆ 56.85    │
│           ┆ Sul       ┆ ido       ┆           ┆   ┆           ┆           ┆           ┆          │
│ …         ┆ …         ┆ …         ┆ …         ┆ … ┆ …         ┆ …         ┆ …         ┆ …        │
│ 146       ┆ Marrocos  ┆ Subdesenv ┆ 51.4      ┆ … ┆ 9.84      ┆ 75.49     ┆ 0.0       ┆ 41.02    │
│           ┆           ┆ olvido    ┆           ┆   ┆           ┆           ┆           ┆          │
│ 147       ┆ Laos      ┆ Subdesenv ┆ 54.88     ┆ … ┆ 8.06      ┆ 67.34     ┆ 0.0       ┆ 24.09    │
│           ┆           ┆ olvido    ┆           ┆   ┆           ┆           ┆           ┆          │
│ 148       ┆ Emirados  ┆ Em desenv ┆ 27.15     ┆ … ┆ 20.71     ┆ 49.84     ┆ 0.0       ┆ 47.64    │
│           ┆ Árabes    ┆ olvimento ┆           ┆   ┆           ┆           ┆           ┆          │
│           ┆ Unidos    ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ 149       ┆ Omã       ┆ Em desenv ┆ 34.31     ┆ … ┆ 14.47     ┆ 54.93     ┆ 0.0       ┆ 50.66    │
│           ┆           ┆ olvimento ┆           ┆   ┆           ┆           ┆           ┆          │
│ 150       ┆ Catar     ┆ Em desenv ┆ 16.3      ┆ … ┆ 9.87      ┆ 50.9      ┆ 0.0       ┆ 41.71    │
│           ┆           ┆ olvimento ┆           ┆   ┆           ┆           ┆           ┆          │
└───────────┴───────────┴───────────┴───────────┴───┴───────────┴───────────┴───────────┴──────────┘

```
Análise: dividino a amostra em duas pequenas partes para usar como exemplo.
```

In [26]:
# Recorte de linhas específicas (linhas 0, 10 e 50)
q_recorte = (
    inicial
    .with_row_index("id_linha")
    .filter(pl.col("id_linha").is_in([0, 10, 50]))
    .select(["id_estudante","pais", "nivel_desenvolvimento", "horas_redes_sociais", "horas_sono"])
)
display(q_recorte.collect())

shape: (3, 5)
┌──────────────┬───────────┬───────────────────────┬─────────────────────┬────────────┐
│ id_estudante ┆ pais      ┆ nivel_desenvolvimento ┆ horas_redes_sociais ┆ horas_sono │
│ ---          ┆ ---       ┆ ---                   ┆ ---                 ┆ ---        │
│ i64          ┆ str       ┆ str                   ┆ f64                 ┆ f64        │
╞══════════════╪═══════════╪═══════════════════════╪═════════════════════╪════════════╡
│ 1            ┆ Catar     ┆ Em desenvolvimento    ┆ 1.1                 ┆ 7.14       │
│ 11           ┆ Dinamarca ┆ Desenvolvido          ┆ 3.94                ┆ 5.73       │
│ 51           ┆ Tanzânia  ┆ Subdesenvolvido       ┆ 3.75                ┆ 5.92       │
└──────────────┴───────────┴───────────────────────┴─────────────────────┴────────────┘

```
Análise: recorte de um estudante aleatório de cada nível de desenvolvimento.
```

### Agrupamento por categoria de uso de redes e horas de sono.
---

In [32]:
# Cruzamento: redes sociais x sono -> bem-estar e frequência
cruz = (
    q_cat.group_by(["categoria_redes", "categoria_sono"])
    .agg(
        pl.len().alias("estudantes"),
        pl.col("indice_bem_estar").mean().round(2).alias("media_bem_estar"),
    )
    .sort(["categoria_redes", "categoria_sono"])
)
display(cruz.collect())

shape: (8, 4)
┌───────────────────┬────────────────┬────────────┬─────────────────┐
│ categoria_redes   ┆ categoria_sono ┆ estudantes ┆ media_bem_estar │
│ ---               ┆ ---            ┆ ---        ┆ ---             │
│ str               ┆ str            ┆ u32        ┆ f64             │
╞═══════════════════╪════════════════╪════════════╪═════════════════╡
│ 1-Baixo (<2h)     ┆ 1-Baixo (≤6h)  ┆ 4141       ┆ 59.04           │
│ 1-Baixo (<2h)     ┆ 2-Médio (6-8h) ┆ 60002      ┆ 66.84           │
│ 1-Baixo (<2h)     ┆ 3-Bom (≥8h)    ┆ 7085       ┆ 74.11           │
│ 2-Moderado (2-5h) ┆ 1-Baixo (≤6h)  ┆ 189735     ┆ 52.74           │
│ 2-Moderado (2-5h) ┆ 2-Médio (6-8h) ┆ 183208     ┆ 61.55           │
│ 2-Moderado (2-5h) ┆ 3-Bom (≥8h)    ┆ 1370       ┆ 70.97           │
│ 3-Alto (≥5h)      ┆ 1-Baixo (≤6h)  ┆ 53285      ┆ 45.15           │
│ 3-Alto (≥5h)      ┆ 2-Médio (6-8h) ┆ 1174       ┆ 54.7            │
└───────────────────┴────────────────┴────────────┴─────────────────┘

```
Análise: conseguimos perceber a partir da amostra acima que, o alto uso de redes sociais impacta tanto na categoria do sono quanto na média de bem-estar.
```

In [33]:
print("=== TESTE 1: Processamento SEM StringCache ===")
start_1 = time.time()

q_sem_cache = (
    pl.scan_parquet("estudantes.parquet")
    .group_by(["pais", "nivel_desenvolvimento"]) 
    .agg([
        pl.col("pontuacao_vicio_digital").mean().alias("media"),
        pl.col("pontuacao_vicio_digital").std().alias("desvio")
    ])
    .sort("media", descending=True)
)

df_1 = q_sem_cache.collect()
end_1 = time.time()

tempo_sem = end_1 - start_1

print(f"Tempo SEM Cache: {tempo_sem:.4f} segundos")
print(f"Uso de memória estimado (coluna pais): {df_1['pais'].estimated_size()} bytes\n")

=== TESTE 1: Processamento SEM StringCache ===
Tempo SEM Cache: 0.0360 segundos
Uso de memória estimado (coluna pais): 428 bytes

In [34]:
print("=== TESTE 2: Processamento COM StringCache ===")
# O StringCache funciona como um contexto (with)
with pl.StringCache():
    start_2 = time.time()

    q_com_cache = (
    pl.scan_parquet("estudantes.parquet")
    .group_by(["pais", "nivel_desenvolvimento"]) 
        .agg([
            pl.col("pontuacao_vicio_digital").mean().alias("media"),
            pl.col("pontuacao_vicio_digital").std().alias("desvio")
        ])
        .sort("media", descending=True)
    )

df_2 = q_com_cache.collect() # Ação!
end_2 = time.time()

tempo_com = end_2 - start_2

print(f"Tempo COM Cache: {tempo_com:.4f} segundos")
print(f"Uso de memória estimado (coluna pais): {df_2['pais'].estimated_size()} bytes\n")

=== TESTE 2: Processamento COM StringCache ===
Tempo COM Cache: 0.0172 segundos
Uso de memória estimado (coluna pais): 428 bytes

C:\Users\indiara.silva\AppData\Local\Temp\ipykernel_19912\3440561067.py:3: DeprecationWarning: the string cache has been replaced by pl.Categories
  with pl.StringCache():